# class Employee(Base):
#     __tablename__ = "employee"
#     id = Column(Integer, primary_key=True)
#     first_name = Column(String)
#     last_name = Column(String)
#     hire_date = Column(Date)
#     birth_date = Column(Date)
#     phone_number = Column(Integer)
#     email = Column(String)
#     location = Column(Integer,ForeignKey("Location.id"))
#     location = relationship("Location", back_populates= "Employee")
#     job = Column(String,ForeignKey("Job.code"))
#     job = relationship("Job", back_populates= "Employee")
#     status_id = Column(String, ForeignKey("EmployeeStatus.id"))
#     status_id = relationship("EmployeeStatus",back_populates="Employee")
#     emp_type = Column(String, ForeignKey("EmployeeType.id"))
#     emp_type = relationship("EmployeeType", back_populates= "Employee")
#     anniversary = Column(Integer,ForeignKey("AnniversaryType.id"))
#     anniversary = relationship("AnniversaryType", back_populates= "Employee")
#     contract = Column(String,ForeignKey("Contract.id"))
#     contract = relationship("Contract", back_populates= "Employee")
#     system_user = relationship("SystemUser", back_populates= "Employee")
#     position_history = relationship("PositionHistory",back_populates="Employee")
#     sep_details = relationship("SeparationDetail", back_populates="Employee")
#     status_history = relationship("StatusHistory", back_populates="Employee")